Add a PRESUBMIT.py script to check pregenerated files
This adds a PRESUBMIT.py script that calls the existing go script to
check pregenerated files. The goal is to catch errors due to
missing/out-of-date pregenerated files earlier, upon commit or upload.
This works with the presubmit API provided by depot_tools, and will only
help you if you use depot_tools to manage local boringssl changes via
`git cl upload`.

(We already run the pregenerate script on CQ via the boringssl.py
recipe. If we had a dedicated builder to run PRESUBMIT.py files on
boringssl CQ via the presubmit recipe (which we don't yet), this script
would also help catch the errors on dry run even earlier, even for folks
not using depot_tools.)


Output looks something like this:

Running presubmit commit checks on branch my-branch-name ...
** Presubmit ERRORS: 1 **
Found out-of-date generated files. Run `go run ./util/pregenerate` to update them.
  Error in file "gen/crypto/chacha-armv4-linux.S": missing file
  Error in file "gen/crypto/aes128gcmsiv-x86_64-linux.S": file out of date
  Error: some files had errors
  exit status 1

Presubmit checks took 1.7s to calculate.
There were presubmit errors.
Was the presubmit check useful? If not, run "git cl presubmit -v"
to figure out which PRESUBMIT.py was run, then run "git blame"
on the file to figure out who to ask for help.

Change-Id: Iad268831ad7353eb15c796906b3f73c12ab8cf80
Reviewed-on: https://boringssl-review.googlesource.com/c/boringssl/+/82867
Auto-Submit: Lily Chen <chlily@google.com>
Commit-Queue: Lily Chen <chlily@google.com>
Reviewed-by: David Benjamin <davidben@google.com>
Commit-Queue: David Benjamin <davidben@google.com>