armv8 assembly: do not branch to global symbols.
This becomes no longer allowed when enabling `.subsections_via_symbols`:

```
error: conditional branch requires assembler-local label. 'vpaes_cbc_decrypt' is external.
```

Bug: 517899061
Change-Id: I69d3a9237a23ccb005d229b05f7d74296a6a6964
Reviewed-on: https://boringssl-review.googlesource.com/c/boringssl/+/96287
Commit-Queue: Rudolf Polzer <rpolzer@google.com>
Reviewed-by: David Benjamin <davidben@google.com>